name: Setup deno environment
runs:
  using: composite
  steps:
    - name: Setup deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Cache Deno dependencies
      id: cache-deno
      uses: actions/cache@v4
      with:
        key: deno-cache-${{ hashFiles('./deno.lock') }}
        path: ${{ env.DENO_DIR }}