name: Setup python environment
description: Install and configure caching for Python environment
runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: pipenv

    - name: Setup pipenv
      shell: bash
      run: |
        pip install pipenv
        pipenv install

