vars:
  - ROOT: ..
  - VOLUNTEER_DATA: ../src/themes/volunteers/_data
stages:
  volunteers:
    cmd: papermill --no-log-output volunteers.ipynb output/volunteers.ipynb
    deps:
      - volunteers.ipynb
      - ../data/published/volunteers/checkpoints.csv
      - ../data/published/volunteers/shifts.csv
    outs:
      - ${VOLUNTEER_DATA}/people/by_demographic_age_range.csv:
          cache: false
      - ${VOLUNTEER_DATA}/people/by_geo_oslaua.csv:
          cache: false
      - ${VOLUNTEER_DATA}/people/by_geo_osward.csv:
          cache: false
      - ${VOLUNTEER_DATA}/people/by_geo_postcode_area.csv:
          cache: false
      - ${VOLUNTEER_DATA}/people/by_geo_TOTAL.csv:
          cache: false
      - ${VOLUNTEER_DATA}/people/checkpoints_weekly.csv:
          cache: false
      - ${VOLUNTEER_DATA}/shifts/attended_by_week.csv:
          cache: false
      - ${VOLUNTEER_DATA}/shifts/attended_cumulative_by_week.csv:
          cache: false
      - ${VOLUNTEER_DATA}/shifts/hours_by_week.csv:
          cache: false
      - ${VOLUNTEER_DATA}/shifts/hours_cumulative_by_week.csv:
          cache: false
  ticketing:
    cmd: papermill --no-log-output ticketing.ipynb output/ticketing.ipynb
    deps:
      - ticketing.ipynb
      - ${ROOT}/data/published/ticketing/tickets.csv
      - ${ROOT}/data/published/ticketing/orders.csv
    outs:
      - ${ROOT}/src/themes/ticketing/_data/operational:
          cache: false