vars:
  - ROOT: ..
  - VOLUNTEER_DATA: ../src/themes/volunteers/_data
stages:
  programme:
    cmd: jupyter execute programme.ipynb
    deps:
      - programme.ipynb
      - utils/themes/programme.py
      - ${ROOT}/data/published/programme/events.csv
      - ${ROOT}/data/published/combined/programme.parquet
    outs:
      - ${ROOT}/src/themes/programme/_data/events/:
          cache: false

  volunteers:
    cmd: papermill --no-log-output volunteers.ipynb output/volunteers.ipynb
    deps:
      - volunteers.ipynb
      - ../data/published/volunteers/checkpoints.csv
      - ../data/published/volunteers/shifts.csv
    outs:
      - ${VOLUNTEER_DATA}/summary.json:
          cache: false
      - ${VOLUNTEER_DATA}/people/by_demographic_age_range.csv:
          cache: false
      - ${VOLUNTEER_DATA}/people/by_geo_oslaua.csv:
          cache: false
      - ${VOLUNTEER_DATA}/people/by_geo_osward.csv:
          cache: false
      - ${VOLUNTEER_DATA}/people/by_geo_postcode_area.csv:
          cache: false
      - ${VOLUNTEER_DATA}/people/by_geo_TOTAL.csv:
          cache: false
      - ${VOLUNTEER_DATA}/people/checkpoints_weekly.csv:
          cache: false
      - ${VOLUNTEER_DATA}/shifts/attended_by_week.csv:
          cache: false
      - ${VOLUNTEER_DATA}/shifts/attended_cumulative_by_week.csv:
          cache: false
      - ${VOLUNTEER_DATA}/shifts/hours_by_week.csv:
          cache: false
      - ${VOLUNTEER_DATA}/shifts/hours_cumulative_by_week.csv:
          cache: false
  ticketing:
    cmd: papermill --no-log-output ticketing.ipynb output/ticketing.ipynb
    deps:
      - ticketing.ipynb
      - ${ROOT}/data/published/ticketing/tickets.csv
      - ${ROOT}/data/published/ticketing/orders.csv
    outs:
      - ${ROOT}/src/themes/ticketing/_data/operational:
          cache: false
  huq:
    cmd: papermill --no-log-output huq.ipynb output/huq.ipynb
    deps:
      - huq.ipynb
      - ${ROOT}/data/huq/mastercard.csv
      - ${ROOT}/data/huq/footfall.long.csv.bz2
    outs:
      - ${ROOT}/src/experiments/huq/_data/footfall_proxy.csv:
          cache: false
      - ${ROOT}/src/experiments/huq/_data/spend_index.csv:
          cache: false

  events:
    # Set this in the `params.yaml` file
    foreach: ${events}
    do:
      cmd: papermill --no-log-output events.ipynb output/events.ipynb
          -p spektrix_event_ids '${item.spektrix_event_ids}'
          -p venue_postcode '${item.venue_postcode}'
          -p rosterfy_event_ids '${item.rosterfy_event_ids}'
          -p project_ids '${item.project_ids}'
          -p evaluation_categories '${item.evaluation_categories}'
          -p venue_ids '${item.venue_ids}'
          -p slug '${key}'
      deps:
        - events.ipynb
        - ${ROOT}/data/published/
        - ${ROOT}/data/published/ticketing/
      outs:
        - ${ROOT}/src/events/${key}/_data/event/:
            cache: false

  sustainability:
    cmd: jupyter execute sustainability.ipynb
    deps:
      - sustainability.ipynb
      - ${ROOT}/data/published/sustainability/calculations.csv
    outs:
      - ${ROOT}/src/themes/sustainability/_data/calculations/:
          cache: false
          persist: true

  dashboards:
    # Set this in the `params.yaml` file
    foreach: ${dashboards}
    do:
      cmd: papermill --no-log-output dashboard.ipynb -
        -p target '${item.target}'
        -p start '${item.start}'
        -p end '${item.end}'
        -p fixed_date '${item.fixed_date}'
      deps:
        - dashboard.ipynb
        - utils/themes/programme.py
        - ${ROOT}/data/published/
      outs:
        - ${ROOT}/src/insights/dashboard/${item.target}/_data/events.json:
            cache: false
            persist: false
        - ${ROOT}/src/insights/dashboard/${item.target}/_data/projects.json:
            cache: false
            persist: false
        - ${ROOT}/src/insights/dashboard/${item.target}/_data/audience.json:
            cache: false
            persist: false
        - ${ROOT}/src/insights/dashboard/${item.target}/_data/timestamp.json:
            cache: false
            persist: false
        - ${ROOT}/src/insights/dashboard/${item.target}/_data/participants.json:
            cache: false
            persist: false
        - ${ROOT}/src/insights/dashboard/${item.target}/_data/otherFigures.json:
            cache: false
            persist: false

  public-dashboard:
    cmd: jupyter execute public-dashboard.ipynb
    deps:
      - public-dashboard.ipynb
      - ${ROOT}/data/published/combined/
    outs:
      - ${ROOT}/src/landing/_data/graph/audiences/total.json:
          cache: false
          persist: false
      - ${ROOT}/src/landing/_data/graph/events/total.json:
          cache: false
          persist: false
      - ${ROOT}/src/landing/_data/graph/participants/total.json:
          cache: false
          persist: false

  digital:
    cmd: jupyter execute digital.ipynb
    deps:
      - public-dashboard.ipynb
      - ${ROOT}/data/published/digital/
    outs:
      - ${ROOT}/src/insights/digital/_data/followers/by_date.json:
          cache: false
      - ${ROOT}/src/insights/digital/_data/followers/latest.json:
          cache: false

  surveys:
    cmd: jupyter execute surveys.ipynb
    deps:
      - surveys.ipynb
      - ${ROOT}/data/published/surveys/responses.csv
    outs:
      - ${ROOT}/src/_data/audience_survey/by_month.json:
          cache: false