events:
  rise:
    project_id: 'recf4tPyjoXi81NDo'
    spektrix_event_ids: '4801ANHPDLLRCQPPBDBQTRQJMPNKSLKPJ'
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '25890'
  la-haine:
    project_id: null
    spektrix_event_ids: '4001APBPRCSHVVMHTCBMSPSJRNDMCHHLV'
    venue_postcode: BD1 1JT
    rosterfy_event_ids: '26307'
  les-girafes:
    project_id: null
    spektrix_event_ids: 'recu2QievPdxr1dnH'
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '24438'
