events:
  rise:
    project_id: 'recf4tPyjoXi81NDo'
    spektrix_event_ids: '4801ANHPDLLRCQPPBDBQTRQJMPNKSLKPJ'
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '25890'
  la-haine:
    project_id: null
    spektrix_event_ids: '4001APBPRCSHVVMHTCBMSPSJRNDMCHHLV'
    venue_postcode: BD1 1JT
    rosterfy_event_ids: '26307'
  les-girafes:
    project_id: null
    spektrix_event_ids: 'recu2QievPdxr1dnH'
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '24438'
  grue:
    project_id: recpLG4BaPUSjpEhJ
    spektrix_event_ids: '7601AHCJPTHNBCVJHLQNKQVKDRKRMLTPC'
    venue_postcode: 
    rosterfy_event_ids: '26540'

dashboards:
  live:
    target: ''
    start: '2025-01-01'
    end: '2025-12-31'
    fixed_date: false
  q1:
    target: q1
    start: '2025-01-01'
    end: '2025-03-31'
    fixed_date: true

