events:
  rise:
    project_ids: 'recf4tPyjoXi81NDo'
    spektrix_event_ids: '4801ANHPDLLRCQPPBDBQTRQJMPNKSLKPJ'
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '25890'
  la-haine:
    project_ids: recYvLfpThEXGXcmn
    spektrix_event_ids: '4001APBPRCSHVVMHTCBMSPSJRNDMCHHLV'
    venue_postcode: BD1 1JT
    rosterfy_event_ids: '26307'
  les-girafes:
    project_ids: recu2QievPdxr1dnH
    spektrix_event_ids: 'recu2QievPdxr1dnH'
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '24438'
  grue:
    project_ids: recoJF8kMXHloBbjt
    spektrix_event_ids: '7601AHCJPTHNBCVJHLQNKQVKDRKRMLTPC'
    venue_postcode: 
    rosterfy_event_ids: '26540'
  dracula:
    project_ids: recjdRJvjmX67plPM
    spektrix_event_ids: '9001AGHDBMPJDRPSRMKLRCJGBJJMTQGDH'
    venue_postcode: 
    rosterfy_event_ids: null
  # loading-bay:
  #   project_ids: recjdRJvjmX67plPM
  #   spektrix_event_ids: null
  #   venue_postcode: 
  #   rosterfy_event_ids: null

dashboards:
  live:
    target: ''
    start: '2025-01-01'
    end: '2025-12-31'
    fixed_date: false
  
  all:
    target: all
    start: '2024-01-01'
    end: '2025-12-31'
    fixed_date: false

  q1:
    target: q1
    start: '2025-01-01'
    end: '2025-03-31'
    fixed_date: true

  q2:
    target: q2
    start: '2025-04-01'
    end: '2025-06-30'
    fixed_date: true
