events:
  rise:
    project_ids: 'recf4tPyjoXi81NDo'
    spektrix_event_ids: '4801ANHPDLLRCQPPBDBQTRQJMPNKSLKPJ'
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '25890'
    venue_ids: ''
  la-haine:
    project_ids: recYvLfpThEXGXcmn
    spektrix_event_ids: '4001APBPRCSHVVMHTCBMSPSJRNDMCHHLV'
    venue_postcode: BD1 1JT
    rosterfy_event_ids: '26307'
    venue_ids: ''
  les-girafes:
    project_ids: recu2QievPdxr1dnH
    spektrix_event_ids: 'recu2QievPdxr1dnH'
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '24438'
    venue_ids: ''
  grue:
    project_ids: recoJF8kMXHloBbjt
    spektrix_event_ids: '7601AHCJPTHNBCVJHLQNKQVKDRKRMLTPC'
    venue_postcode: 
    rosterfy_event_ids: '26540'
    venue_ids: ''
  dracula:
    project_ids: recjdRJvjmX67plPM
    spektrix_event_ids: '9001AGHDBMPJDRPSRMKLRCJGBJJMTQGDH'
    venue_postcode: 
    rosterfy_event_ids: null
    venue_ids: ''
  loading-bay:
    project_ids: ''
    spektrix_event_ids: ''
    venue_postcode: 
    rosterfy_event_ids: ''
    venue_ids: 'rec4maUwKspPcDxNl recFYiOZvNnYDgbfk recInFDrcQ4KutUcL recIrQ1v64zKajXU1 recalzwrAJkBYOz8w'
  beacon:
    project_ids: ''
    spektrix_event_ids: ''
    venue_postcode: 
    rosterfy_event_ids: ''
    venue_ids: 'rec7tn1K6r85N72yc recW1DV5uXWsrUShy recea0GEE29eKCtxu recx817GdO7wmJDf6'
  the-bradford-progress:
    project_ids: 'recSACUvnIn3yCW2S'
    spektrix_event_ids: ''
    venue_postcode: 
    rosterfy_event_ids: '29424'
    venue_ids: ''

dashboards:
  live:
    target: ''
    start: '2025-01-01'
    end: '2025-12-31'
    fixed_date: false
  
  all:
    target: all
    start: '2024-01-01'
    end: '2025-12-31'
    fixed_date: false

  q1:
    target: q1
    start: '2025-01-01'
    end: '2025-03-31'
    fixed_date: true

  q2:
    target: q2
    start: '2025-04-01'
    end: '2025-06-30'
    fixed_date: true
