events:
  rise:
    project_ids: 'recf4tPyjoXi81NDo'
    evaluation_categories: ''
    spektrix_event_ids: '4801ANHPDLLRCQPPBDBQTRQJMPNKSLKPJ'
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '25890'
    venue_ids: ''
  la-haine:
    project_ids: recYvLfpThEXGXcmn
    evaluation_categories: ''
    spektrix_event_ids: '4001APBPRCSHVVMHTCBMSPSJRNDMCHHLV'
    venue_postcode: BD1 1JT
    rosterfy_event_ids: '26307'
    venue_ids: ''
  les-girafes:
    project_ids: recu2QievPdxr1dnH
    evaluation_categories: ''
    spektrix_event_ids: 'recu2QievPdxr1dnH'
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '24438'
    venue_ids: ''
  grue:
    project_ids: recoJF8kMXHloBbjt
    evaluation_categories: ''
    spektrix_event_ids: '7601AHCJPTHNBCVJHLQNKQVKDRKRMLTPC'
    venue_postcode: 
    rosterfy_event_ids: '26540'
    venue_ids: ''
  dracula:
    project_ids: recjdRJvjmX67plPM
    evaluation_categories: ''
    spektrix_event_ids: '9001AGHDBMPJDRPSRMKLRCJGBJJMTQGDH'
    venue_postcode: 
    rosterfy_event_ids: null
    venue_ids: ''
  loading-bay:
    project_ids: ''
    evaluation_categories: ''
    spektrix_event_ids: ''
    venue_postcode: 
    rosterfy_event_ids: ''
    venue_ids: 'rec4maUwKspPcDxNl recCTkADG9VERRhxt recFYiOZvNnYDgbfk recInFDrcQ4KutUcL recIrQ1v64zKajXU1 recalzwrAJkBYOz8w'
  beacon:
    project_ids: ''
    evaluation_categories: ''
    spektrix_event_ids: ''
    venue_postcode: 
    rosterfy_event_ids: ''
    venue_ids: 'recx817GdO7wmJDf6 rec7tn1K6r85N72yc recea0GEE29eKCtxu recW1DV5uXWsrUShy'
  the-bradford-progress:
    project_ids: 'recSACUvnIn3yCW2S'
    evaluation_categories: ''
    spektrix_event_ids: ''
    venue_postcode: 
    rosterfy_event_ids: '29424'
    venue_ids: ''
  woodland-tribe:
    project_ids: 'rec6linWPrAEi0gwr'
    evaluation_categories: ''
    spektrix_event_ids: '13201ACQQNNPSNRJMNQRQRCSJCCGPQLHJ'
    venue_postcode: ''
    rosterfy_event_ids: ''
    venue_ids: ''
  film:
    project_ids: ''
    evaluation_categories: 'Film'
    spektrix_event_ids: ''
    venue_postcode: ''
    rosterfy_event_ids: ''
    venue_ids: ''
  contains-strong-language:
    project_ids: 'recHt86hDKkVGecCP'
    evaluation_categories: ''
    spektrix_event_ids: '64601AHJJJGRPPGBJRDJBKDBVLLBQMRLP 64801AJPTMMJGDJQHDKQNBCGKMVGLSGLB 65001ABJBLQTSTGTMVKPRRHSLPSVNVDBM 65201ACRNVHVJBDMGRPJPBKVMQHKPTNJN 65401ARRMBSGBRKRMPJDLPDLGHVCMRJJP 65002ASPDRDSNLPMSGLJDNVNGKQNNJKJM 65601ABJVQCQRNKJTHQGGNGBHPDGVBKKD 64602AQLNMGNSJPNDHMTVGPDNVRRJDRCV 65801ABDQQTPTQHTDJVCCJNHQLNRJJCBG 65202AGSSSKQLRKGHGMLHSDNNNSRKSGQN 64603AQQJBRKGRBTKNDCCTRVBBLMKSGPC 65203ARKDJGBKLPGTVQKHQGMLSCSVVCMS 66001AJSDDCKQDHCCKMMQLSPQJHHDNNSR 65802ATSHJMDCBCNQSPMPBSCBGMTRCNKL 65803ACDRLMMRHGGPGVKPCJPKQJNMDTMQ 66201ANBJCCNMNTBQVCLNSBCLHRLCHCHL 66401ABGHVCPGPCLVNGNMHHVHCCMPBDSP 66601AGQCGDBVSBRBPDBPSKRTDHMKTVRL 66002AMJRRKMLMKQRPHRPCNVGRCJTPPSC 66801AQKPRHKKGQQBTMBVQVVTVMKKQTGN 67001APKGPVRDVBKMDCRCRMPHDNRDBKDN 67201AVCRKQDBSGLQHRCLJQTBDLCTLNNQ 67401ALTRTTRTPTSQHLNNDTGHMDRBCNBR 64604ARKDSJQGBNLTJQLVLJCNNNGSJJJL 66602AKVTPDMRQBBTMRQMJTBNHPPKRKMJ 67601AVHPCSTMMBKTGKLCGLQQCGMMBVSK 66802ALTBGLDQGCMRJNMSJMTRHHLCHHCQ 66402AQSGKVVNKGTGDDCQQRVHVTCPGDRN 67602AGRNQSGNGVNNJGBCCMVRNLPVLHRN 67801ATCLBJSLNJHDDQMPHBVVCKNGLMHB 69201ARPJLTNJBTLLMTLRNMQHNSVKNBHM 69801ACHMQQPHNNNRPKGGCKPVPDJPPBTJ 70001AMJRQHDGBRNVCKLMQDNCHKHNLGPL 70201ADHVPVLHCVCVCTRPRPPPJCCSKTGL 69802AGMDGRMVVMRNBNDDRDCLTQTNLCBH 70401ASVSQQQCRPSCNRQPCKDQQQTGLMGK 70601ARTMQVDQNBCQNBNVCVCNCQVKTRPG 69402ARHVPHVRBNRRQVBCNDVGQPGBVNLQ 69403ADGLQNJBMTSRBPBGTHMDGNDCCSCL 70801ACCPCJTVQVGBDPKMJGLRTJJDDVBG 71001AGBBMCNTJHLGBJRQPPQJJCSTSQBR 65803ACDRLMMRHGGPGVKPCJPKQJNMDTMQ 66801AQKPRHKKGQQBTMBVQVVTVMKKQTGN'
    venue_postcode: ''
    rosterfy_event_ids: ''
    venue_ids: ''

dashboards:
  live:
    target: ''
    start: '2023-01-01'
    end: '2025-12-31'
    fixed_date: 'false'
  
  q1:
    target: q1
    start: '2025-01-01'
    end: '2025-03-31'
    fixed_date: 'true'

  q2:
    target: q2
    start: '2025-04-01'
    end: '2025-06-30'
    fixed_date: 'true'

  q3:
    target: q3
    start: '2025-07-01'
    end: '2025-09-30'
    fixed_date: 'true'
