events:
  rise:
    spektrix_event_ids: '4801ANHPDLLRCQPPBDBQTRQJMPNKSLKPJ'
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '25890'
  la-haine:
    spektrix_event_ids: '4001APBPRCSHVVMHTCBMSPSJRNDMCHHLV'
    venue_postcode: BD1 1JT
    rosterfy_event_ids: '26307'
  les-girafes:
    spektrix_event_ids: ''
    venue_postcode: BD1 1LA
    rosterfy_event_ids: '24438'
