const config = {
  apiKey: "b53693c0e57af918717ff18bfc4af753763c4659",
  product: "PRO",
  logConsent: true,
  notifyOnce: false,
  initialState: "NOTIFY",
  position: "RIGHT",
  theme: "DARK",
  layout: "SLIDEOUT",
  toggleType: "slider",
  acceptBehaviour: "all",
  closeOnGlobalChange: true,
  iabCMP: false,
  closeStyle: "icon",
  consentCookieExpiry: 90,
  subDomains: true,
  mode: "gdpr",
  rejectButton: true,
  settingsStyle: "button",
  encodeCookie: false,
  setInnerHTML: true,
  wrapInnerHTML: false,
  accessibility: {
    accessKey: "C",
    highlightFocus: false,
    outline: true,
    overlay: true,
    disableSiteScrolling: false,
  },
  text: {
    title: "This site uses cookies",
    intro:
      "The Bradford 2025 UK City of Culture websites use cookies. Some of these cookies are essential, while others help us to improve your experience by providing insights into how the site is being used.",
    necessaryTitle: "Necessary Cookies",
    necessaryDescription:
      "Our website and ticketing system cannot function properly without these cookies. They can only be disabled by changing your browser preferences.",
    thirdPartyTitle: "Some cookies require your attention",
    thirdPartyDescription:
      "Consent for the following cookies could not be automatically revoked. Please follow the link(s) below to opt out manually.",
    on: "On",
    off: "Off",
    accept: "Accept",
    settings: "Cookie Preferences",
    acceptRecommended: "Accept Recommended Settings",
    acceptSettings: "I Accept",
    notifyTitle: "This site uses cookies",
    notifyDescription:
      "We use cookies to optimise this site's functionality and give you the best possible experience.",
    closeLabel: "Close",
    cornerButton: "Set cookie preferences.",
    landmark: "Cookie preferences.",
    showVendors: "Show vendors within this category",
    thirdPartyCookies: "This vendor may set third party cookies.",
    readMore: "Read more",
    accessibilityAlert:
      "This site uses cookies to store information. Press accesskey C to learn more about your options.",
    rejectSettings: "Reject All",
    reject: "Reject",
  },

  branding: {
    fontColor: "#262626",
    fontFamily: "Denim INK, sans-serif",
    fontSizeTitle: "1.5em",
    fontSizeHeaders: "1.1em",
    fontSize: "0.9em",
    backgroundColor: "#ffffff",
    toggleText: "#cecece",
    toggleColor: "#f4accd",
    toggleBackground: "#434343",
    alertText: "#434343",
    alertBackground: "#262626",
    acceptText: "#262626",
    acceptBackground: "#f4accd",
    rejectText: "#ffffff",
    rejectBackground: "#434343",
    closeText: "#262626",
    closeBackground: "#434343",
    notifyFontColor: "#1c1c1c",
    notifyBackgroundColor: "#e8e8e8",
    buttonIcon: null,
    buttonIconWidth: "64px",
    buttonIconHeight: "64px",
    removeIcon: false,
    removeAbout: false,
  },

  necessaryCookies: [
    // "wordpress_*",
    // "wordpress_logged_in_*",
    // "CookieControl",
    // "wp_consent_*",
    // "QueueNumber",
    // "SessionId",
    // "CookieDetection",
    // "SpektrixClientName",
    // ".ASPXAUTH",
    // "cf_clearance",
    // "__cf_bm",
    // "simplified",
    // "darkMode",
    // "textSize",
    // "SIDCC",
    // "SEARCH_SAMESITE",
  ],

  optionalCookies: [
    {
      name: "analytics",
      label: "Analytics cookies",
      description:
        "We use analytics cookies to track how people use our website to help us improve it in future.",
      cookies: [
        "_ga",
        "_ga_F7V05TJ56H",
        "ReturningCustomerCookie",
        "_ga_REQ3NYFJZK",
      ],
      onAccept: function () {
      },
      onRevoke: function () {
      },
      recommendedState: "off",
      lawfulBasis: "consent",
    },
    // {
    //   name: "marketing",
    //   label: "Marketing cookies",
    //   description:
    //     "We use marketing cookies to track our marketing campaign activity.",
    //   cookies: [
    //     "tt_enable_cookie",
    //     "_ttp",
    //     "AEC",
    //     "HSID",
    //     "SSID",
    //     "SAPISID",
    //     "NID",
    //     "APSID",
    //     "DSID",
    //     "IDE",
    //     "ar_debug",
    //     "_fbp",
    //     "xs",
    //   ],
    //   onAccept: function () {
    //   },
    //   onRevoke: function () {
    //   },
    //   recommendedState: "off",
    //   lawfulBasis: "consent",
    // },
  ],
  statement: {
    description: "For more information, please see our",
    name: "Privacy Policy.",
    url: "https://bradford2025.co.uk/privacy-policy/",
    updated: "12/12/2024",
  },
  sameSiteCookie: true,
  sameSiteValue: "Strict",
  notifyDismissButton: true,
};

globalThis.CookieControl.load(config);
