- topic: Cultural engagement and participation
  tag: evaluation
  system:
    - Airtable?
  dataset:
    - events
    - attendees

- topic: Volunteering
  tag: evaluation
  system:
    - Rosterfy
  dataset:
    - signups
    - shifts

- topic: Cultural sector diversity and sustainability
  tag: evaluation
- topic: Economy and tourism
  tag: evaluation
- topic: Personal wellbeing
  tag: evaluation
- topic: Community wellbeing and civic pride
  tag: evaluation
- topic: Environment
  tag: evaluation
- topic: Learning culture
  tag: evaluation

# Operational

- topic: Projects
  dataset:
    - evaluations

- topic: Events
  system:
    - Airtable?
  dataset:
    - schedule
    - audience numbers
    - programme segment
    - location

- topic: Ticketing
  dataset:
    - orders
    - tickets

- topic: Attendee feedback
  system:
    - Typeform
  dataset:
    - summary feedback

- topic: Call outs
  system:
    - Typeform?
  dataset:
    - applications

- topic: Education programme
  system:
    - Airtable?
  dataset:
    - events
    - attendees

- topic: Media coverage
  system:
    - Cision (via AMA)? 
  dataset:
    - articles

- topic: Social media
  system:
    - Instagram
    - TikTok
    - Facebook
    - Twitter/X
    - YouTube
    - LinkedIn
  dataset:
    - audience
    - engagements

- topic: Web analytics
  system:
    - Google Analytics (GTM)
  dataset:
    - unique views
    - visitors
