- topic: Events
  system:
    - Airtable?
  dataset:
    - schedule
    - audience numbers
    - programme segment
    - location

- topic: Ticketing
  dataset:
    - orders
    - tickets

- topic: Attendee feedback
  system:
    - Typeform
  dataset:
    - summary feedback

- topic: Volunteering
  system:
    - Rosterfy
  dataset:
    - signups
    - shifts

- topic: Community engagement
  system:
    - Airtable?
  dataset:
    - events
    - attendees

- topic: Education programme
  system:
    - Airtable?
  dataset:
    - events
    - attendees

- topic: Call outs
  system:
    - Typeform?
  dataset:
    - applications

- topic: Media coverage
  system:
    - Cision (via AMA)? 
  dataset:
    - articles

- topic: Social media
  system:
    - Instagram
    - TikTok
    - Facebook
    - Twitter/X
    - YouTube
    - LinkedIn
  dataset:
    - audience
    - engagements

- topic: Web analytics
  system:
    - Google Analytics (GTM)
  dataset:
    - unique views
    - visitors
