# For this to work, the Source for GitHub Pages needs to be set to GitHub Actions
# This setting is in Settings -> Pages on the repo GitHub page

name: Build site

'on':
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - src/**
      - _config.ts
      - deno.json
      - .github/workflows/build-site.yml

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    # Packaged action to build a Lume site. See https://github.com/dringtech/lume-build
    steps:

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pipenv

      - name: Setup pipenv
        run: |
          pip install pipenv
          pipenv install

      - name: Get current data
        run: |
          umask 077
          eval $(ssh-agent -s)

          echo "${{ secrets.DEPLOY_KEY }}" > deploy-key
          ssh-add deploy-key
          pipenv run dvc update data/published.dvc data/metadata.dvc
          ssh-add -D

          echo "${{ secrets.DEPLOY_KEY_HUQ }}" > deploy-key-huq
          ssh-add deploy-key-huq          
          pipenv run dvc update data/huq.dvc
          ssh-add -D

      - name: Run pipelines
        run: |
          pipenv run dvc repro pipelines/dvc.yaml

      - name: Build the site
        uses: dringtech/lume-build@v3
        with:
          site-build-cmd: deno task build
          deno-version: v2.x

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    # You need to set up GitHub Pages to deploy from an action
    # See https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow for documentation
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4